// <auto-generated />
using System;
using Employee_Storage.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee_Storage.Migrations
{
    [DbContext(typeof(EmployeeDBcontext))]
    partial class EmployeeDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Employee_Storage.Models.Department", b =>
                {
                    b.Property<int>("dept_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("department_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dept_id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Employee_Storage.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("departmentdept_id")
                        .HasColumnType("int");

                    b.Property<string>("desgination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("departmentdept_id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Employee_Storage.Models.Employee", b =>
                {
                    b.HasOne("Employee_Storage.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("departmentdept_id");

                    b.Navigation("department");
                });
#pragma warning restore 612, 618
        }
    }
}
